### ISSUE TITLE
EET Compatibility Notes

### ISSUE THREAD

**Issue by Endarire** [Black-Wyrm-Lair/ToB-Tourist#1]
Note that EET (Enhanced Edition Trilogy) should allow you to access all areas unlocked already.  Thus, if you started your game in BG1, SoD, or SoA, you can return to the SoA areas once they're unlocked to you.  This mod could be useful on EET if you play EET but start in the ToB section.

**Comment by Roberciiik** [comment]
Thank you, I will add this notice to the README.

**Comment by Roberciiik** [comment]
Included in v3.
